### PR TITLE
Cloudlinux fixes

### PR DESCRIPTION
**Pull request by stefanmortensen**
This commit finish the initial installation of a CloudLinux web server set up for shared configuration to allow clustering.

It also sets up a central PostgreSQL database for storing statistics from lvestats for integration with Daggre.

### CODE REVIEW

**Comment by nbeernink** [comment]
Shame travis doesn't approve. ;) Fixed it for you in https://github.com/stefanmortensen/puppet-atomia/pull/1

But wouldn't it be cleaner to template the lvestats file instead of using complicated sedding around? I tried looking for a puppet module that manages lvestats but there doesn't seem to be one around yet. So that might be the quickest and cleanest option?

**Comment by stefanmortensen** [comment]
Thanks, I noticed but didn't have time to fix it yesterday.

In general I don't like using templates for configuration files (even though we do it alot) for maintainability reasons. Say that one user would like to change/add something to the configuration file that is overwritten by the template. The only way to do it would be to fork the puppet module and change the template file making his copy out of sync with the master repo. Augeas is the best alternative for general configuration files and where Augeas support is lacking i think that sedding the specific configuration values is a reasonable option.

**Comment by nbeernink** [comment]
Agreed, I forgot atomia only does single runs for installation. In that case augeas (or sed via exec) is a better tool I suppose. 

In our own environment we have puppet running as a daemon so anything that's not in a template will be removed to ensure we're running the config that we want.

**Comment by stefanmortensen** [comment]
I'd like it to be a reasonable option to keep using the module to manage the environment after the installation. I however do not like to force configuration options (not really related to Atomia) without any reasonable option to override. We could of course have some sort of manifest for managing the configuration file by optionally passing setting variables (with reasonable defaults) but until then I think we should try to force only settings that are required and leave the rest as optional for the user to define with his own Puppet module.

**Comment by nbeernink** [comment]
I think the use-case you describe is doable via for example:

https://github.com/puppetlabs/puppetlabs-apache#custom_fragment
or
https://github.com/puppetlabs/puppetlabs-mysql#customize-server-options

It's just a list of defined options with an ability to add another option which allows additional non-templated options. The override would then still be done through puppet though.

Another alternative is to add an additional config file that gets parsed along the way, but not all software knows how to do this. It seems lvestats does know how to do this though: 

http://docs.cloudlinux.com/index.html?configuration2.html
http://docs.cloudlinux.com/index.html?plugin_configuration.html

**Comment by stefanmortensen** [comment]
I like the way it is done in the puppetlabs-mysql example. I'll look into this some more to see what is the most reasonable way. Thanks!

**Pull request merged**
