### PR TITLE
Issue 113

### LINKED ISSUE #113: Initial provisioning of Active Directory server fails
It seems to finish eventually but fails on the first run
Output from Puppet:

[0;32mInfo: Loading facts[0m
[0;32mInfo: Caching catalog for win-a2hffcq1mft.eu-west-1.compute.internal[0m
[0;32mInfo: Applying configuration version '1465461822'[0m
[mNotice: /Stage[main]/Nsclient::Install/File[c:\temp]/ensure: created[0m
[mNotice: /Stage[main]/Atomia::Active_directory/File[c:/install]/ensure: created[0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[Install AD forest]/returns: executed successfully[0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-conditional-forwarder-internaldns]/returns: executed successfully[0m
[mNotice: /Stage[main]/Atomia::Active_directory/File[c:/install/add_users.ps1]/ensure: defined content as '{md5}2e57461c971d52f4dc01f859bc138d27'[0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns: Get-ADUser : The term 'Get-ADUser' is not recognized as the name of a cmdlet, [0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns: function, script file, or operable program. Check the spelling of the name, or [0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns: if a path was included, verify that the path is correct and try again.[0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns: At C:\install\add_users.ps1:22 char:13[0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns: +     $user = Get-ADUser $aduser -Properties Name,DistinguishedName[0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns: +             ~~~~~~~~~~[0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns:     + CategoryInfo          : ObjectNotFound: (Get-ADUser:String) [], CommandN [0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns:    otFoundException[0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns:     + FullyQualifiedErrorId : CommandNotFoundException[0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns:  [0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns: Add-ADGroupMember : The term 'Add-ADGroupMember' is not recognized as the name [0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns: of a cmdlet, function, script file, or operable program. Check the spelling of [0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns: the name, or if a path was included, verify that the path is correct and try [0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns: again.[0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns: At C:\install\add_users.ps1:129 char:9[0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns: +         Add-ADGroupMember "Domain Admins" "apppooluser"[0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns: +         ~~~~~~~~~~~~~~~~~[0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns:     + CategoryInfo          : ObjectNotFound: (Add-ADGroupMember:String) [], C [0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns:    ommandNotFoundException[0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns:     + FullyQualifiedErrorId : CommandNotFoundException[0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns:  [0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns: Account: apppooluser[0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns: Account not found![0m
[mNotice: /Stage[main]/Atomia::Bootstrap/File[C:\ProgramData\PuppetLabs\facter\facts.d\atomia_role.ps1]/ensure: defined content as '{md5}54b3b9babf6b868d621ef0e7f6c90f1c'[0m
[mNotice: /Stage[main]/Atomia::Active_directory/File[C:\ProgramData\PuppetLabs\facter\facts.d\atomia_role_ad.ps1]/ensure: defined content as '{md5}eb5d094361ab4a0c22ca0d0df137ca51'[0m
[mNotice: /Stage[main]/Atomia::Active_directory/File[c:/install/sync_time.ps1]/ensure: defined content as '{md5}1b12b3689dce75215c97484a14ef012a'[0m
stderr: [1;31mError: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -executionpolicy remotesigned -file c:/install/add_users.ps1 returned 4294967295 instead of one of [0][0m
[1;31mError: /Stage[main]/Atomia::Active_directory/Exec[add-ad-users]/returns: change from notrun to 0 failed: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -executionpolicy remotesigned -file c:/install/add_users.ps1 returned 4294967295 instead of one of [0][0m
[mNotice: /Stage[main]/Atomia::Active_directory/Exec[sync-time]/returns: executed successfully[0m
[mNotice: /Stage[main]/Nsclient::Install/Download_file[NSCP-Installer]/File[download-NSCP-0.4.4.15-x64.msi.ps1]/ensure: created[0m
[mNotice: /Stage[main]/Nsclient::Install/Download_file[NSCP-Installer]/Exec[download-NSCP-0.4.4.15-x64.msi]/returns: executed successfully[0m
[mNotice: /Stage[main]/Nsclient::Install/Package[NSClient++ (x64)]/ensure: created[0m
[mNotice: /Stage[main]/Nsclient::Service/File[C:\Program Files\NSClient++\nsclient.ini]/content: 
[0m
[0;32mInfo: Computing checksum on file C:/Program Files/NSClient++/nsclient.ini[0m
[0;32mInfo: /Stage[main]/Nsclient::Service/File[C:\Program Files\NSClient++\nsclient.ini]: Filebucketed C:/Program Files/NSClient++/nsclient.ini to puppet with sum 699fe3f4d128ec941fbd96116241d3bd[0m
[mNotice: /Stage[main]/Nsclient::Service/File[C:\Program Files\NSClient++\nsclient.ini]/content: content changed '{md5}699fe3f4d128ec941fbd96116241d3bd' to '{md5}e5f634fa8f1a87ee8d62400b00b306e0'[0m
[mNotice: /Stage[main]/Nsclient::Service/File[C:\Program Files\NSClient++\nsclient.ini]/mode: mode changed '2000770' to '0664'[0m
[0;32mInfo: Creating state file C:/ProgramData/PuppetLabs/puppet/var/state/state.yaml[0m
[mNotice: Finished catalog run in 21.61 seconds[0m
Command exited with code: 6
Error while provisioning. Server might not work fully, please try to run provisioning again

### PR DESCRIPTION
**Pull request by stefanmortensen**
Fix #113

### CODE REVIEW

**Comment by stefanmortensen** [comment]
@nbeernink No worries :) 

Looks like travis does complain but the rake tasks exits with 0 

manifests/active_directory.pp:81:variable_scope:WARNING:top-scope variable being used without an explicit namespace
manifests/active_directory.pp:146:variable_scope:WARNING:top-scope variable being used without an explicit namespace
The command "bundle exec rake" exited with 0.

**Comment by nbeernink** [comment]
Ah.. I see now. it's because of warnings and puppet-lint's fail_on_warnings defaults to false.

Could add it to Rakefile to have travis complain, but then I'm not sure how to properly escape the command.

**Comment by stefanmortensen** [comment]
Unsure as well, changing the outer double quotes to single quotes shows a different warning about variable within single quotes :). I'll see if perhaps the Powershell command can be modified a bit.

**Comment by stefanmortensen** [comment]
Modified it a bit with #115, it now passes validation

**Pull request merged**
