### PR TITLE
Added gRPC options to the windows_base manifest and ini_template

### PR DESCRIPTION
**Pull request by oscarlinderholm**

### CODE REVIEW

**Comment by stefanmortensen** [comment]
@oscarlinderholm What is the probability of someone needing to change these variables? Seeing the amount of new variables and how it would clutter the GUI I'm thinking it might make sense to add "%hide" as the validation value (see https://github.com/atomia/puppet-atomia/blob/master/manifests/windows_base.pp#L51). This would hide it completely from the GUI. You could still override it by using the hiera YAML files.

**Comment by oscarlinderholm** [comment]
It is likely that you would like to change the whitelist variables for example so that only a certain range and/or ip addresses can access the endpoint. They are however added as advanced options so they should not be shown unless the advanced button is clicked.

**Comment by stefanmortensen** [comment]
Ok fair enough :)

**Comment by jimmybergman** [comment]
Even better would be if we could figure out a way to restrict to the IPs of app and gui servers by default. Now that we add all servers first and configure after, things like that feels possible without too much hassle.

Skickat från min iPhone

**Comment by stefanmortensen** [comment]
I was thinking the same actually, it is pretty simple. By adding %ipaddress in the validation field for some variable the ip will be resolved by the gui application and stored in the hiera backend. We could then create the whitelist based on the ipaddress variables from the application servers by concatenating the variables from hiera.

**Pull request merged**
